development:
  adapter: postgresql
  database: denisisa_admin41
  pool: 5
  timeout: 5000
  username: denisisa_admin41
  password: admin
  host: postgresql2.locum.ru

test:
  adapter: postgresql
  database: denisisa_admin41
  pool: 5
  timeout: 5000
  username: denisisa_admin41
  password: admin
  host: postgresql2.locum.ru

production:
  adapter: postgresql
  database: denisisa_admin41
  pool: 5
  timeout: 5000
  username: denisisa_admin41
  password: admin
  host: postgresql2.locum.ru

remote_db:
  adapter: postgresql
  host: 185.31.160.161
  port: 5432
  database: fusionpbx
  username: webclient
  password: test