development:
  adapter: postgresql
  database: test
  pool: 5
  timeout: 5000
  username: test
  password: test
  host: localhost

test:
  adapter: postgresql
  database: test
  pool: 5
  timeout: 5000
  username: test
  password: test
  host: localhost

production:
  adapter: postgresql
  database: test
  pool: 5
  timeout: 5000
  username: test
  password: test
  host: localhost

remote_db:
  adapter: postgresql
  host: 185.31.160.161
  port: 5432
  database: fusionpbx
  username: webclient
  password: test