development:
  adapter: postgresql
  database: admin_panel
  pool: 5
  timeout: 5000
  username: admin
  password: admin
  host: localhost

test:
  adapter: sqlite3
  database: admin_panel
  pool: 5
  timeout: 5000

production:
  adapter: sqlite3
  database: db/production.sqlite3
  pool: 5
  timeout: 5000

remote_db:
  adapter: postgresql
  host: 185.31.160.161
  port: 5432
  database: fusionpbx
  username: webclient
  password: test